import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import Card from "../components/Card";

import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Next js Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="col justify-center items-center p-8 pt-24">
        <div className="md:w-1/2">
          <h1 className="text-center">
            <span>Next js </span>Blog
          </h1>
          <div className="py-12 res-row">
            <Card name="Hello world" />
            <Card name="Hello world" />
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
